spring:
    profiles:
        active: dev
    application:
        name: mynews-service
    jpa:
        hibernate:
            ddl-auto: create
        defer-datasource-initialization: false
        show-sql: true
        open-in-view: false
